export class HourlyJSON {
  // model for HourlyJSON, don't actually need to fill fields in
  '@context': [
    'https://geojson.org/geojson-ld/geojson-context.jsonld',
    {
      '@version': string,
      'wx': string,
      'geo': string,
      'unit': string,
      '@vocab': string
    }
  ];
  'type': string;
  'geometry': {
    'type': string,
    'coordinates': [
      [
        [
          number,
          number
        ],
        [
          number,
          number
        ],
        [
          number,
          number
        ],
        [
          number,
          number
        ],
        [
          number,
          number
        ]
      ]
    ]
  };
  'properties': {
    'updated': string,
    'units': string,
    'forecastGenerator': string,
    'generatedAt': string,
    'updateTime': string,
    'validTimes': string,
    'elevation': {
      'value': number,
      'unitCode': string
    },
    'periods': [
      {
        'number': 1,
        'name': '',
        'startTime': string,
        'endTime': string,
        'isDaytime': boolean,
        'temperature': number,
        'temperatureUnit': 'F',
        'temperatureTrend': null,
        'windSpeed': string,
        'windDirection': string,
        'icon': string,
        'shortForecast': string,
        'detailedForecast': ''
      },
      {
        'number': 2,
        'name': '',
        'startTime': '2020-09-23T12:00:00-07:00',
        'endTime': '2020-09-23T13:00:00-07:00',
        'isDaytime': true,
        'temperature': 74,
        'temperatureUnit': 'F',
        'temperatureTrend': null,
        'windSpeed': '7 mph',
        'windDirection': 'NNW',
        'icon': 'https://api.weather.gov/icons/land/day/skc?size=small',
        'shortForecast': 'Sunny',
        'detailedForecast': ''
      },
      {
        'number': 3,
        'name': '',
        'startTime': '2020-09-23T13:00:00-07:00',
        'endTime': '2020-09-23T14:00:00-07:00',
        'isDaytime': true,
        'temperature': 76,
        'temperatureUnit': 'F',
        'temperatureTrend': null,
        'windSpeed': '8 mph',
        'windDirection': 'NNW',
        'icon': 'https://api.weather.gov/icons/land/day/skc?size=small',
        'shortForecast': 'Sunny',
        'detailedForecast': ''
      },
      {
        'number': 4,
        'name': '',
        'startTime': '2020-09-23T14:00:00-07:00',
        'endTime': '2020-09-23T15:00:00-07:00',
        'isDaytime': true,
        'temperature': 77,
        'temperatureUnit': 'F',
        'temperatureTrend': null,
        'windSpeed': '10 mph',
        'windDirection': 'NNW',
        'icon': 'https://api.weather.gov/icons/land/day/skc?size=small',
        'shortForecast': 'Sunny',
        'detailedForecast': ''
      },
      {
        'number': 5,
        'name': '',
        'startTime': '2020-09-23T15:00:00-07:00',
        'endTime': '2020-09-23T16:00:00-07:00',
        'isDaytime': true,
        'temperature': 77,
        'temperatureUnit': 'F',
        'temperatureTrend': null,
        'windSpeed': '10 mph',
        'windDirection': 'NNW',
        'icon': 'https://api.weather.gov/icons/land/day/skc?size=small',
        'shortForecast': 'Sunny',
        'detailedForecast': ''
      },
      {
        'number': 6,
        'name': '',
        'startTime': '2020-09-23T16:00:00-07:00',
        'endTime': '2020-09-23T17:00:00-07:00',
        'isDaytime': true,
        'temperature': 78,
        'temperatureUnit': 'F',
        'temperatureTrend': null,
        'windSpeed': '10 mph',
        'windDirection': 'NNW',
        'icon': 'https://api.weather.gov/icons/land/day/skc?size=small',
        'shortForecast': 'Sunny',
        'detailedForecast': ''
      },
      {
        'number': 7,
        'name': '',
        'startTime': '2020-09-23T17:00:00-07:00',
        'endTime': '2020-09-23T18:00:00-07:00',
        'isDaytime': true,
        'temperature': 75,
        'temperatureUnit': 'F',
        'temperatureTrend': null,
        'windSpeed': '10 mph',
        'windDirection': 'NNW',
        'icon': 'https://api.weather.gov/icons/land/day/skc?size=small',
        'shortForecast': 'Sunny',
        'detailedForecast': ''
      },
      {
        'number': 8,
        'name': '',
        'startTime': '2020-09-23T18:00:00-07:00',
        'endTime': '2020-09-23T19:00:00-07:00',
        'isDaytime': false,
        'temperature': 73,
        'temperatureUnit': 'F',
        'temperatureTrend': null,
        'windSpeed': '10 mph',
        'windDirection': 'NNW',
        'icon': 'https://api.weather.gov/icons/land/night/skc?size=small',
        'shortForecast': 'Clear',
        'detailedForecast': ''
      },
      {
        'number': 9,
        'name': '',
        'startTime': '2020-09-23T19:00:00-07:00',
        'endTime': '2020-09-23T20:00:00-07:00',
        'isDaytime': false,
        'temperature': 68,
        'temperatureUnit': 'F',
        'temperatureTrend': null,
        'windSpeed': '9 mph',
        'windDirection': 'NNW',
        'icon': 'https://api.weather.gov/icons/land/night/skc?size=small',
        'shortForecast': 'Clear',
        'detailedForecast': ''
      },
      {
        'number': 10,
        'name': '',
        'startTime': '2020-09-23T20:00:00-07:00',
        'endTime': '2020-09-23T21:00:00-07:00',
        'isDaytime': false,
        'temperature': 66,
        'temperatureUnit': 'F',
        'temperatureTrend': null,
        'windSpeed': '7 mph',
        'windDirection': 'NW',
        'icon': 'https://api.weather.gov/icons/land/night/few?size=small',
        'shortForecast': 'Mostly Clear',
        'detailedForecast': ''
      },
      {
        'number': 11,
        'name': '',
        'startTime': '2020-09-23T21:00:00-07:00',
        'endTime': '2020-09-23T22:00:00-07:00',
        'isDaytime': false,
        'temperature': 63,
        'temperatureUnit': 'F',
        'temperatureTrend': null,
        'windSpeed': '6 mph',
        'windDirection': 'NW',
        'icon': 'https://api.weather.gov/icons/land/night/few?size=small',
        'shortForecast': 'Mostly Clear',
        'detailedForecast': ''
      },
      {
        'number': 12,
        'name': '',
        'startTime': '2020-09-23T22:00:00-07:00',
        'endTime': '2020-09-23T23:00:00-07:00',
        'isDaytime': false,
        'temperature': 63,
        'temperatureUnit': 'F',
        'temperatureTrend': null,
        'windSpeed': '5 mph',
        'windDirection': 'NW',
        'icon': 'https://api.weather.gov/icons/land/night/sct?size=small',
        'shortForecast': 'Partly Cloudy',
        'detailedForecast': ''
      },
      {
        'number': 13,
        'name': '',
        'startTime': '2020-09-23T23:00:00-07:00',
        'endTime': '2020-09-24T00:00:00-07:00',
        'isDaytime': false,
        'temperature': 62,
        'temperatureUnit': 'F',
        'temperatureTrend': null,
        'windSpeed': '3 mph',
        'windDirection': 'WNW',
        'icon': 'https://api.weather.gov/icons/land/night/bkn?size=small',
        'shortForecast': 'Mostly Cloudy',
        'detailedForecast': ''
      },
      {
        'number': 14,
        'name': '',
        'startTime': '2020-09-24T00:00:00-07:00',
        'endTime': '2020-09-24T01:00:00-07:00',
        'isDaytime': false,
        'temperature': 62,
        'temperatureUnit': 'F',
        'temperatureTrend': null,
        'windSpeed': '3 mph',
        'windDirection': 'WNW',
        'icon': 'https://api.weather.gov/icons/land/night/bkn?size=small',
        'shortForecast': 'Mostly Cloudy',
        'detailedForecast': ''
      },
      {
        'number': 15,
        'name': '',
        'startTime': '2020-09-24T01:00:00-07:00',
        'endTime': '2020-09-24T02:00:00-07:00',
        'isDaytime': false,
        'temperature': 62,
        'temperatureUnit': 'F',
        'temperatureTrend': null,
        'windSpeed': '2 mph',
        'windDirection': 'WNW',
        'icon': 'https://api.weather.gov/icons/land/night/bkn?size=small',
        'shortForecast': 'Mostly Cloudy',
        'detailedForecast': ''
      },
      {
        'number': 16,
        'name': '',
        'startTime': '2020-09-24T02:00:00-07:00',
        'endTime': '2020-09-24T03:00:00-07:00',
        'isDaytime': false,
        'temperature': 62,
        'temperatureUnit': 'F',
        'temperatureTrend': null,
        'windSpeed': '2 mph',
        'windDirection': 'WNW',
        'icon': 'https://api.weather.gov/icons/land/night/bkn?size=small',
        'shortForecast': 'Mostly Cloudy',
        'detailedForecast': ''
      },
      {
        'number': 17,
        'name': '',
        'startTime': '2020-09-24T03:00:00-07:00',
        'endTime': '2020-09-24T04:00:00-07:00',
        'isDaytime': false,
        'temperature': 62,
        'temperatureUnit': 'F',
        'temperatureTrend': null,
        'windSpeed': '2 mph',
        'windDirection': 'WNW',
        'icon': 'https://api.weather.gov/icons/land/night/bkn?size=small',
        'shortForecast': 'Mostly Cloudy',
        'detailedForecast': ''
      },
      {
        'number': 18,
        'name': '',
        'startTime': '2020-09-24T04:00:00-07:00',
        'endTime': '2020-09-24T05:00:00-07:00',
        'isDaytime': false,
        'temperature': 62,
        'temperatureUnit': 'F',
        'temperatureTrend': null,
        'windSpeed': '2 mph',
        'windDirection': 'WNW',
        'icon': 'https://api.weather.gov/icons/land/night/bkn?size=small',
        'shortForecast': 'Mostly Cloudy',
        'detailedForecast': ''
      },
      {
        'number': 19,
        'name': '',
        'startTime': '2020-09-24T05:00:00-07:00',
        'endTime': '2020-09-24T06:00:00-07:00',
        'isDaytime': false,
        'temperature': 62,
        'temperatureUnit': 'F',
        'temperatureTrend': null,
        'windSpeed': '3 mph',
        'windDirection': 'WNW',
        'icon': 'https://api.weather.gov/icons/land/night/bkn?size=small',
        'shortForecast': 'Mostly Cloudy',
        'detailedForecast': ''
      },
      {
        'number': 20,
        'name': '',
        'startTime': '2020-09-24T06:00:00-07:00',
        'endTime': '2020-09-24T07:00:00-07:00',
        'isDaytime': true,
        'temperature': 62,
        'temperatureUnit': 'F',
        'temperatureTrend': null,
        'windSpeed': '3 mph',
        'windDirection': 'WNW',
        'icon': 'https://api.weather.gov/icons/land/day/bkn?size=small',
        'shortForecast': 'Mostly Cloudy',
        'detailedForecast': ''
      },
      {
        'number': 21,
        'name': '',
        'startTime': '2020-09-24T07:00:00-07:00',
        'endTime': '2020-09-24T08:00:00-07:00',
        'isDaytime': true,
        'temperature': 62,
        'temperatureUnit': 'F',
        'temperatureTrend': null,
        'windSpeed': '3 mph',
        'windDirection': 'WNW',
        'icon': 'https://api.weather.gov/icons/land/day/bkn?size=small',
        'shortForecast': 'Mostly Cloudy',
        'detailedForecast': ''
      },
      {
        'number': 22,
        'name': '',
        'startTime': '2020-09-24T08:00:00-07:00',
        'endTime': '2020-09-24T09:00:00-07:00',
        'isDaytime': true,
        'temperature': 62,
        'temperatureUnit': 'F',
        'temperatureTrend': null,
        'windSpeed': '5 mph',
        'windDirection': 'NW',
        'icon': 'https://api.weather.gov/icons/land/day/bkn?size=small',
        'shortForecast': 'Partly Sunny',
        'detailedForecast': ''
      },
      {
        'number': 23,
        'name': '',
        'startTime': '2020-09-24T09:00:00-07:00',
        'endTime': '2020-09-24T10:00:00-07:00',
        'isDaytime': true,
        'temperature': 63,
        'temperatureUnit': 'F',
        'temperatureTrend': null,
        'windSpeed': '5 mph',
        'windDirection': 'NW',
        'icon': 'https://api.weather.gov/icons/land/day/bkn?size=small',
        'shortForecast': 'Partly Sunny',
        'detailedForecast': ''
      },
      {
        'number': 24,
        'name': '',
        'startTime': '2020-09-24T10:00:00-07:00',
        'endTime': '2020-09-24T11:00:00-07:00',
        'isDaytime': true,
        'temperature': 65,
        'temperatureUnit': 'F',
        'temperatureTrend': null,
        'windSpeed': '5 mph',
        'windDirection': 'NW',
        'icon': 'https://api.weather.gov/icons/land/day/bkn?size=small',
        'shortForecast': 'Partly Sunny',
        'detailedForecast': ''
      },
      {
        'number': 25,
        'name': '',
        'startTime': '2020-09-24T11:00:00-07:00',
        'endTime': '2020-09-24T12:00:00-07:00',
        'isDaytime': true,
        'temperature': 67,
        'temperatureUnit': 'F',
        'temperatureTrend': null,
        'windSpeed': '6 mph',
        'windDirection': 'NW',
        'icon': 'https://api.weather.gov/icons/land/day/sct?size=small',
        'shortForecast': 'Mostly Sunny',
        'detailedForecast': ''
      },
      {
        'number': 26,
        'name': '',
        'startTime': '2020-09-24T12:00:00-07:00',
        'endTime': '2020-09-24T13:00:00-07:00',
        'isDaytime': true,
        'temperature': 70,
        'temperatureUnit': 'F',
        'temperatureTrend': null,
        'windSpeed': '6 mph',
        'windDirection': 'NW',
        'icon': 'https://api.weather.gov/icons/land/day/sct?size=small',
        'shortForecast': 'Mostly Sunny',
        'detailedForecast': ''
      },
      {
        'number': 27,
        'name': '',
        'startTime': '2020-09-24T13:00:00-07:00',
        'endTime': '2020-09-24T14:00:00-07:00',
        'isDaytime': true,
        'temperature': 72,
        'temperatureUnit': 'F',
        'temperatureTrend': null,
        'windSpeed': '6 mph',
        'windDirection': 'NW',
        'icon': 'https://api.weather.gov/icons/land/day/sct?size=small',
        'shortForecast': 'Mostly Sunny',
        'detailedForecast': ''
      },
      {
        'number': 28,
        'name': '',
        'startTime': '2020-09-24T14:00:00-07:00',
        'endTime': '2020-09-24T15:00:00-07:00',
        'isDaytime': true,
        'temperature': 75,
        'temperatureUnit': 'F',
        'temperatureTrend': null,
        'windSpeed': '10 mph',
        'windDirection': 'NW',
        'icon': 'https://api.weather.gov/icons/land/day/few?size=small',
        'shortForecast': 'Sunny',
        'detailedForecast': ''
      },
      {
        'number': 29,
        'name': '',
        'startTime': '2020-09-24T15:00:00-07:00',
        'endTime': '2020-09-24T16:00:00-07:00',
        'isDaytime': true,
        'temperature': 76,
        'temperatureUnit': 'F',
        'temperatureTrend': null,
        'windSpeed': '10 mph',
        'windDirection': 'NW',
        'icon': 'https://api.weather.gov/icons/land/day/few?size=small',
        'shortForecast': 'Sunny',
        'detailedForecast': ''
      },
      {
        'number': 30,
        'name': '',
        'startTime': '2020-09-24T16:00:00-07:00',
        'endTime': '2020-09-24T17:00:00-07:00',
        'isDaytime': true,
        'temperature': 76,
        'temperatureUnit': 'F',
        'temperatureTrend': null,
        'windSpeed': '10 mph',
        'windDirection': 'NW',
        'icon': 'https://api.weather.gov/icons/land/day/few?size=small',
        'shortForecast': 'Sunny',
        'detailedForecast': ''
      },
      {
        'number': 31,
        'name': '',
        'startTime': '2020-09-24T17:00:00-07:00',
        'endTime': '2020-09-24T18:00:00-07:00',
        'isDaytime': true,
        'temperature': 75,
        'temperatureUnit': 'F',
        'temperatureTrend': null,
        'windSpeed': '12 mph',
        'windDirection': 'WNW',
        'icon': 'https://api.weather.gov/icons/land/day/few?size=small',
        'shortForecast': 'Sunny',
        'detailedForecast': ''
      },
      {
        'number': 32,
        'name': '',
        'startTime': '2020-09-24T18:00:00-07:00',
        'endTime': '2020-09-24T19:00:00-07:00',
        'isDaytime': false,
        'temperature': 72,
        'temperatureUnit': 'F',
        'temperatureTrend': null,
        'windSpeed': '12 mph',
        'windDirection': 'WNW',
        'icon': 'https://api.weather.gov/icons/land/night/few?size=small',
        'shortForecast': 'Mostly Clear',
        'detailedForecast': ''
      },
      {
        'number': 33,
        'name': '',
        'startTime': '2020-09-24T19:00:00-07:00',
        'endTime': '2020-09-24T20:00:00-07:00',
        'isDaytime': false,
        'temperature': 68,
        'temperatureUnit': 'F',
        'temperatureTrend': null,
        'windSpeed': '12 mph',
        'windDirection': 'WNW',
        'icon': 'https://api.weather.gov/icons/land/night/few?size=small',
        'shortForecast': 'Mostly Clear',
        'detailedForecast': ''
      },
      {
        'number': 34,
        'name': '',
        'startTime': '2020-09-24T20:00:00-07:00',
        'endTime': '2020-09-24T21:00:00-07:00',
        'isDaytime': false,
        'temperature': 65,
        'temperatureUnit': 'F',
        'temperatureTrend': null,
        'windSpeed': '8 mph',
        'windDirection': 'WNW',
        'icon': 'https://api.weather.gov/icons/land/night/few?size=small',
        'shortForecast': 'Mostly Clear',
        'detailedForecast': ''
      },
      {
        'number': 35,
        'name': '',
        'startTime': '2020-09-24T21:00:00-07:00',
        'endTime': '2020-09-24T22:00:00-07:00',
        'isDaytime': false,
        'temperature': 64,
        'temperatureUnit': 'F',
        'temperatureTrend': null,
        'windSpeed': '8 mph',
        'windDirection': 'WNW',
        'icon': 'https://api.weather.gov/icons/land/night/few?size=small',
        'shortForecast': 'Mostly Clear',
        'detailedForecast': ''
      },
      {
        'number': 36,
        'name': '',
        'startTime': '2020-09-24T22:00:00-07:00',
        'endTime': '2020-09-24T23:00:00-07:00',
        'isDaytime': false,
        'temperature': 63,
        'temperatureUnit': 'F',
        'temperatureTrend': null,
        'windSpeed': '8 mph',
        'windDirection': 'WNW',
        'icon': 'https://api.weather.gov/icons/land/night/few?size=small',
        'shortForecast': 'Mostly Clear',
        'detailedForecast': ''
      },
      {
        'number': 37,
        'name': '',
        'startTime': '2020-09-24T23:00:00-07:00',
        'endTime': '2020-09-25T00:00:00-07:00',
        'isDaytime': false,
        'temperature': 62,
        'temperatureUnit': 'F',
        'temperatureTrend': null,
        'windSpeed': '6 mph',
        'windDirection': 'W',
        'icon': 'https://api.weather.gov/icons/land/night/few?size=small',
        'shortForecast': 'Mostly Clear',
        'detailedForecast': ''
      },
      {
        'number': 38,
        'name': '',
        'startTime': '2020-09-25T00:00:00-07:00',
        'endTime': '2020-09-25T01:00:00-07:00',
        'isDaytime': false,
        'temperature': 61,
        'temperatureUnit': 'F',
        'temperatureTrend': null,
        'windSpeed': '6 mph',
        'windDirection': 'W',
        'icon': 'https://api.weather.gov/icons/land/night/few?size=small',
        'shortForecast': 'Mostly Clear',
        'detailedForecast': ''
      },
      {
        'number': 39,
        'name': '',
        'startTime': '2020-09-25T01:00:00-07:00',
        'endTime': '2020-09-25T02:00:00-07:00',
        'isDaytime': false,
        'temperature': 60,
        'temperatureUnit': 'F',
        'temperatureTrend': null,
        'windSpeed': '6 mph',
        'windDirection': 'W',
        'icon': 'https://api.weather.gov/icons/land/night/few?size=small',
        'shortForecast': 'Mostly Clear',
        'detailedForecast': ''
      },
      {
        'number': 40,
        'name': '',
        'startTime': '2020-09-25T02:00:00-07:00',
        'endTime': '2020-09-25T03:00:00-07:00',
        'isDaytime': false,
        'temperature': 59,
        'temperatureUnit': 'F',
        'temperatureTrend': null,
        'windSpeed': '5 mph',
        'windDirection': 'W',
        'icon': 'https://api.weather.gov/icons/land/night/few?size=small',
        'shortForecast': 'Mostly Clear',
        'detailedForecast': ''
      },
      {
        'number': 41,
        'name': '',
        'startTime': '2020-09-25T03:00:00-07:00',
        'endTime': '2020-09-25T04:00:00-07:00',
        'isDaytime': false,
        'temperature': 59,
        'temperatureUnit': 'F',
        'temperatureTrend': null,
        'windSpeed': '5 mph',
        'windDirection': 'W',
        'icon': 'https://api.weather.gov/icons/land/night/few?size=small',
        'shortForecast': 'Mostly Clear',
        'detailedForecast': ''
      },
      {
        'number': 42,
        'name': '',
        'startTime': '2020-09-25T04:00:00-07:00',
        'endTime': '2020-09-25T05:00:00-07:00',
        'isDaytime': false,
        'temperature': 58,
        'temperatureUnit': 'F',
        'temperatureTrend': null,
        'windSpeed': '5 mph',
        'windDirection': 'W',
        'icon': 'https://api.weather.gov/icons/land/night/few?size=small',
        'shortForecast': 'Mostly Clear',
        'detailedForecast': ''
      },
      {
        'number': 43,
        'name': '',
        'startTime': '2020-09-25T05:00:00-07:00',
        'endTime': '2020-09-25T06:00:00-07:00',
        'isDaytime': false,
        'temperature': 58,
        'temperatureUnit': 'F',
        'temperatureTrend': null,
        'windSpeed': '3 mph',
        'windDirection': 'W',
        'icon': 'https://api.weather.gov/icons/land/night/sct?size=small',
        'shortForecast': 'Partly Cloudy',
        'detailedForecast': ''
      },
      {
        'number': 44,
        'name': '',
        'startTime': '2020-09-25T06:00:00-07:00',
        'endTime': '2020-09-25T07:00:00-07:00',
        'isDaytime': true,
        'temperature': 57,
        'temperatureUnit': 'F',
        'temperatureTrend': null,
        'windSpeed': '3 mph',
        'windDirection': 'W',
        'icon': 'https://api.weather.gov/icons/land/day/sct?size=small',
        'shortForecast': 'Mostly Sunny',
        'detailedForecast': ''
      },
      {
        'number': 45,
        'name': '',
        'startTime': '2020-09-25T07:00:00-07:00',
        'endTime': '2020-09-25T08:00:00-07:00',
        'isDaytime': true,
        'temperature': 57,
        'temperatureUnit': 'F',
        'temperatureTrend': null,
        'windSpeed': '3 mph',
        'windDirection': 'W',
        'icon': 'https://api.weather.gov/icons/land/day/sct?size=small',
        'shortForecast': 'Mostly Sunny',
        'detailedForecast': ''
      },
      {
        'number': 46,
        'name': '',
        'startTime': '2020-09-25T08:00:00-07:00',
        'endTime': '2020-09-25T09:00:00-07:00',
        'isDaytime': true,
        'temperature': 57,
        'temperatureUnit': 'F',
        'temperatureTrend': null,
        'windSpeed': '3 mph',
        'windDirection': 'W',
        'icon': 'https://api.weather.gov/icons/land/day/sct?size=small',
        'shortForecast': 'Mostly Sunny',
        'detailedForecast': ''
      },
      {
        'number': 47,
        'name': '',
        'startTime': '2020-09-25T09:00:00-07:00',
        'endTime': '2020-09-25T10:00:00-07:00',
        'isDaytime': true,
        'temperature': 60,
        'temperatureUnit': 'F',
        'temperatureTrend': null,
        'windSpeed': '3 mph',
        'windDirection': 'W',
        'icon': 'https://api.weather.gov/icons/land/day/sct?size=small',
        'shortForecast': 'Mostly Sunny',
        'detailedForecast': ''
      },
      {
        'number': 48,
        'name': '',
        'startTime': '2020-09-25T10:00:00-07:00',
        'endTime': '2020-09-25T11:00:00-07:00',
        'isDaytime': true,
        'temperature': 63,
        'temperatureUnit': 'F',
        'temperatureTrend': null,
        'windSpeed': '3 mph',
        'windDirection': 'W',
        'icon': 'https://api.weather.gov/icons/land/day/sct?size=small',
        'shortForecast': 'Mostly Sunny',
        'detailedForecast': ''
      },
      {
        'number': 49,
        'name': '',
        'startTime': '2020-09-25T11:00:00-07:00',
        'endTime': '2020-09-25T12:00:00-07:00',
        'isDaytime': true,
        'temperature': 66,
        'temperatureUnit': 'F',
        'temperatureTrend': null,
        'windSpeed': '6 mph',
        'windDirection': 'WNW',
        'icon': 'https://api.weather.gov/icons/land/day/few?size=small',
        'shortForecast': 'Sunny',
        'detailedForecast': ''
      },
      {
        'number': 50,
        'name': '',
        'startTime': '2020-09-25T12:00:00-07:00',
        'endTime': '2020-09-25T13:00:00-07:00',
        'isDaytime': true,
        'temperature': 70,
        'temperatureUnit': 'F',
        'temperatureTrend': null,
        'windSpeed': '6 mph',
        'windDirection': 'WNW',
        'icon': 'https://api.weather.gov/icons/land/day/few?size=small',
        'shortForecast': 'Sunny',
        'detailedForecast': ''
      },
      {
        'number': 51,
        'name': '',
        'startTime': '2020-09-25T13:00:00-07:00',
        'endTime': '2020-09-25T14:00:00-07:00',
        'isDaytime': true,
        'temperature': 73,
        'temperatureUnit': 'F',
        'temperatureTrend': null,
        'windSpeed': '6 mph',
        'windDirection': 'WNW',
        'icon': 'https://api.weather.gov/icons/land/day/few?size=small',
        'shortForecast': 'Sunny',
        'detailedForecast': ''
      },
      {
        'number': 52,
        'name': '',
        'startTime': '2020-09-25T14:00:00-07:00',
        'endTime': '2020-09-25T15:00:00-07:00',
        'isDaytime': true,
        'temperature': 76,
        'temperatureUnit': 'F',
        'temperatureTrend': null,
        'windSpeed': '9 mph',
        'windDirection': 'WNW',
        'icon': 'https://api.weather.gov/icons/land/day/few?size=small',
        'shortForecast': 'Sunny',
        'detailedForecast': ''
      },
      {
        'number': 53,
        'name': '',
        'startTime': '2020-09-25T15:00:00-07:00',
        'endTime': '2020-09-25T16:00:00-07:00',
        'isDaytime': true,
        'temperature': 78,
        'temperatureUnit': 'F',
        'temperatureTrend': null,
        'windSpeed': '9 mph',
        'windDirection': 'WNW',
        'icon': 'https://api.weather.gov/icons/land/day/few?size=small',
        'shortForecast': 'Sunny',
        'detailedForecast': ''
      },
      {
        'number': 54,
        'name': '',
        'startTime': '2020-09-25T16:00:00-07:00',
        'endTime': '2020-09-25T17:00:00-07:00',
        'isDaytime': true,
        'temperature': 79,
        'temperatureUnit': 'F',
        'temperatureTrend': null,
        'windSpeed': '9 mph',
        'windDirection': 'WNW',
        'icon': 'https://api.weather.gov/icons/land/day/few?size=small',
        'shortForecast': 'Sunny',
        'detailedForecast': ''
      },
      {
        'number': 55,
        'name': '',
        'startTime': '2020-09-25T17:00:00-07:00',
        'endTime': '2020-09-25T18:00:00-07:00',
        'isDaytime': true,
        'temperature': 77,
        'temperatureUnit': 'F',
        'temperatureTrend': null,
        'windSpeed': '12 mph',
        'windDirection': 'WNW',
        'icon': 'https://api.weather.gov/icons/land/day/few?size=small',
        'shortForecast': 'Sunny',
        'detailedForecast': ''
      },
      {
        'number': 56,
        'name': '',
        'startTime': '2020-09-25T18:00:00-07:00',
        'endTime': '2020-09-25T19:00:00-07:00',
        'isDaytime': false,
        'temperature': 74,
        'temperatureUnit': 'F',
        'temperatureTrend': null,
        'windSpeed': '12 mph',
        'windDirection': 'WNW',
        'icon': 'https://api.weather.gov/icons/land/night/few?size=small',
        'shortForecast': 'Mostly Clear',
        'detailedForecast': ''
      },
      {
        'number': 57,
        'name': '',
        'startTime': '2020-09-25T19:00:00-07:00',
        'endTime': '2020-09-25T20:00:00-07:00',
        'isDaytime': false,
        'temperature': 70,
        'temperatureUnit': 'F',
        'temperatureTrend': null,
        'windSpeed': '12 mph',
        'windDirection': 'WNW',
        'icon': 'https://api.weather.gov/icons/land/night/few?size=small',
        'shortForecast': 'Mostly Clear',
        'detailedForecast': ''
      },
      {
        'number': 58,
        'name': '',
        'startTime': '2020-09-25T20:00:00-07:00',
        'endTime': '2020-09-25T21:00:00-07:00',
        'isDaytime': false,
        'temperature': 66,
        'temperatureUnit': 'F',
        'temperatureTrend': null,
        'windSpeed': '7 mph',
        'windDirection': 'W',
        'icon': 'https://api.weather.gov/icons/land/night/few?size=small',
        'shortForecast': 'Mostly Clear',
        'detailedForecast': ''
      },
      {
        'number': 59,
        'name': '',
        'startTime': '2020-09-25T21:00:00-07:00',
        'endTime': '2020-09-25T22:00:00-07:00',
        'isDaytime': false,
        'temperature': 64,
        'temperatureUnit': 'F',
        'temperatureTrend': null,
        'windSpeed': '7 mph',
        'windDirection': 'W',
        'icon': 'https://api.weather.gov/icons/land/night/few?size=small',
        'shortForecast': 'Mostly Clear',
        'detailedForecast': ''
      },
      {
        'number': 60,
        'name': '',
        'startTime': '2020-09-25T22:00:00-07:00',
        'endTime': '2020-09-25T23:00:00-07:00',
        'isDaytime': false,
        'temperature': 62,
        'temperatureUnit': 'F',
        'temperatureTrend': null,
        'windSpeed': '7 mph',
        'windDirection': 'W',
        'icon': 'https://api.weather.gov/icons/land/night/few?size=small',
        'shortForecast': 'Mostly Clear',
        'detailedForecast': ''
      },
      {
        'number': 61,
        'name': '',
        'startTime': '2020-09-25T23:00:00-07:00',
        'endTime': '2020-09-26T00:00:00-07:00',
        'isDaytime': false,
        'temperature': 62,
        'temperatureUnit': 'F',
        'temperatureTrend': null,
        'windSpeed': '3 mph',
        'windDirection': 'W',
        'icon': 'https://api.weather.gov/icons/land/night/skc?size=small',
        'shortForecast': 'Clear',
        'detailedForecast': ''
      },
      {
        'number': 62,
        'name': '',
        'startTime': '2020-09-26T00:00:00-07:00',
        'endTime': '2020-09-26T01:00:00-07:00',
        'isDaytime': false,
        'temperature': 61,
        'temperatureUnit': 'F',
        'temperatureTrend': null,
        'windSpeed': '3 mph',
        'windDirection': 'W',
        'icon': 'https://api.weather.gov/icons/land/night/skc?size=small',
        'shortForecast': 'Clear',
        'detailedForecast': ''
      },
      {
        'number': 63,
        'name': '',
        'startTime': '2020-09-26T01:00:00-07:00',
        'endTime': '2020-09-26T02:00:00-07:00',
        'isDaytime': false,
        'temperature': 61,
        'temperatureUnit': 'F',
        'temperatureTrend': null,
        'windSpeed': '3 mph',
        'windDirection': 'W',
        'icon': 'https://api.weather.gov/icons/land/night/skc?size=small',
        'shortForecast': 'Clear',
        'detailedForecast': ''
      },
      {
        'number': 64,
        'name': '',
        'startTime': '2020-09-26T02:00:00-07:00',
        'endTime': '2020-09-26T03:00:00-07:00',
        'isDaytime': false,
        'temperature': 60,
        'temperatureUnit': 'F',
        'temperatureTrend': null,
        'windSpeed': '2 mph',
        'windDirection': 'W',
        'icon': 'https://api.weather.gov/icons/land/night/few?size=small',
        'shortForecast': 'Mostly Clear',
        'detailedForecast': ''
      },
      {
        'number': 65,
        'name': '',
        'startTime': '2020-09-26T03:00:00-07:00',
        'endTime': '2020-09-26T04:00:00-07:00',
        'isDaytime': false,
        'temperature': 60,
        'temperatureUnit': 'F',
        'temperatureTrend': null,
        'windSpeed': '2 mph',
        'windDirection': 'W',
        'icon': 'https://api.weather.gov/icons/land/night/few?size=small',
        'shortForecast': 'Mostly Clear',
        'detailedForecast': ''
      },
      {
        'number': 66,
        'name': '',
        'startTime': '2020-09-26T04:00:00-07:00',
        'endTime': '2020-09-26T05:00:00-07:00',
        'isDaytime': false,
        'temperature': 60,
        'temperatureUnit': 'F',
        'temperatureTrend': null,
        'windSpeed': '2 mph',
        'windDirection': 'W',
        'icon': 'https://api.weather.gov/icons/land/night/few?size=small',
        'shortForecast': 'Mostly Clear',
        'detailedForecast': ''
      },
      {
        'number': 67,
        'name': '',
        'startTime': '2020-09-26T05:00:00-07:00',
        'endTime': '2020-09-26T06:00:00-07:00',
        'isDaytime': false,
        'temperature': 60,
        'temperatureUnit': 'F',
        'temperatureTrend': null,
        'windSpeed': '2 mph',
        'windDirection': 'NW',
        'icon': 'https://api.weather.gov/icons/land/night/few?size=small',
        'shortForecast': 'Mostly Clear',
        'detailedForecast': ''
      },
      {
        'number': 68,
        'name': '',
        'startTime': '2020-09-26T06:00:00-07:00',
        'endTime': '2020-09-26T07:00:00-07:00',
        'isDaytime': true,
        'temperature': 59,
        'temperatureUnit': 'F',
        'temperatureTrend': null,
        'windSpeed': '2 mph',
        'windDirection': 'NW',
        'icon': 'https://api.weather.gov/icons/land/day/few?size=small',
        'shortForecast': 'Sunny',
        'detailedForecast': ''
      },
      {
        'number': 69,
        'name': '',
        'startTime': '2020-09-26T07:00:00-07:00',
        'endTime': '2020-09-26T08:00:00-07:00',
        'isDaytime': true,
        'temperature': 60,
        'temperatureUnit': 'F',
        'temperatureTrend': null,
        'windSpeed': '2 mph',
        'windDirection': 'NW',
        'icon': 'https://api.weather.gov/icons/land/day/few?size=small',
        'shortForecast': 'Sunny',
        'detailedForecast': ''
      },
      {
        'number': 70,
        'name': '',
        'startTime': '2020-09-26T08:00:00-07:00',
        'endTime': '2020-09-26T09:00:00-07:00',
        'isDaytime': true,
        'temperature': 62,
        'temperatureUnit': 'F',
        'temperatureTrend': null,
        'windSpeed': '5 mph',
        'windDirection': 'N',
        'icon': 'https://api.weather.gov/icons/land/day/few?size=small',
        'shortForecast': 'Sunny',
        'detailedForecast': ''
      },
      {
        'number': 71,
        'name': '',
        'startTime': '2020-09-26T09:00:00-07:00',
        'endTime': '2020-09-26T10:00:00-07:00',
        'isDaytime': true,
        'temperature': 66,
        'temperatureUnit': 'F',
        'temperatureTrend': null,
        'windSpeed': '5 mph',
        'windDirection': 'N',
        'icon': 'https://api.weather.gov/icons/land/day/few?size=small',
        'shortForecast': 'Sunny',
        'detailedForecast': ''
      },
      {
        'number': 72,
        'name': '',
        'startTime': '2020-09-26T10:00:00-07:00',
        'endTime': '2020-09-26T11:00:00-07:00',
        'isDaytime': true,
        'temperature': 70,
        'temperatureUnit': 'F',
        'temperatureTrend': null,
        'windSpeed': '5 mph',
        'windDirection': 'N',
        'icon': 'https://api.weather.gov/icons/land/day/few?size=small',
        'shortForecast': 'Sunny',
        'detailedForecast': ''
      },
      {
        'number': 73,
        'name': '',
        'startTime': '2020-09-26T11:00:00-07:00',
        'endTime': '2020-09-26T12:00:00-07:00',
        'isDaytime': true,
        'temperature': 75,
        'temperatureUnit': 'F',
        'temperatureTrend': null,
        'windSpeed': '8 mph',
        'windDirection': 'NNW',
        'icon': 'https://api.weather.gov/icons/land/day/skc?size=small',
        'shortForecast': 'Sunny',
        'detailedForecast': ''
      },
      {
        'number': 74,
        'name': '',
        'startTime': '2020-09-26T12:00:00-07:00',
        'endTime': '2020-09-26T13:00:00-07:00',
        'isDaytime': true,
        'temperature': 80,
        'temperatureUnit': 'F',
        'temperatureTrend': null,
        'windSpeed': '8 mph',
        'windDirection': 'NNW',
        'icon': 'https://api.weather.gov/icons/land/day/skc?size=small',
        'shortForecast': 'Sunny',
        'detailedForecast': ''
      },
      {
        'number': 75,
        'name': '',
        'startTime': '2020-09-26T13:00:00-07:00',
        'endTime': '2020-09-26T14:00:00-07:00',
        'isDaytime': true,
        'temperature': 83,
        'temperatureUnit': 'F',
        'temperatureTrend': null,
        'windSpeed': '8 mph',
        'windDirection': 'NNW',
        'icon': 'https://api.weather.gov/icons/land/day/skc?size=small',
        'shortForecast': 'Sunny',
        'detailedForecast': ''
      },
      {
        'number': 76,
        'name': '',
        'startTime': '2020-09-26T14:00:00-07:00',
        'endTime': '2020-09-26T15:00:00-07:00',
        'isDaytime': true,
        'temperature': 86,
        'temperatureUnit': 'F',
        'temperatureTrend': null,
        'windSpeed': '12 mph',
        'windDirection': 'NW',
        'icon': 'https://api.weather.gov/icons/land/day/skc?size=small',
        'shortForecast': 'Sunny',
        'detailedForecast': ''
      },
      {
        'number': 77,
        'name': '',
        'startTime': '2020-09-26T15:00:00-07:00',
        'endTime': '2020-09-26T16:00:00-07:00',
        'isDaytime': true,
        'temperature': 88,
        'temperatureUnit': 'F',
        'temperatureTrend': null,
        'windSpeed': '12 mph',
        'windDirection': 'NW',
        'icon': 'https://api.weather.gov/icons/land/day/skc?size=small',
        'shortForecast': 'Sunny',
        'detailedForecast': ''
      },
      {
        'number': 78,
        'name': '',
        'startTime': '2020-09-26T16:00:00-07:00',
        'endTime': '2020-09-26T17:00:00-07:00',
        'isDaytime': true,
        'temperature': 88,
        'temperatureUnit': 'F',
        'temperatureTrend': null,
        'windSpeed': '12 mph',
        'windDirection': 'NW',
        'icon': 'https://api.weather.gov/icons/land/day/skc?size=small',
        'shortForecast': 'Sunny',
        'detailedForecast': ''
      },
      {
        'number': 79,
        'name': '',
        'startTime': '2020-09-26T17:00:00-07:00',
        'endTime': '2020-09-26T18:00:00-07:00',
        'isDaytime': true,
        'temperature': 87,
        'temperatureUnit': 'F',
        'temperatureTrend': null,
        'windSpeed': '13 mph',
        'windDirection': 'NW',
        'icon': 'https://api.weather.gov/icons/land/day/skc?size=small',
        'shortForecast': 'Sunny',
        'detailedForecast': ''
      },
      {
        'number': 80,
        'name': '',
        'startTime': '2020-09-26T18:00:00-07:00',
        'endTime': '2020-09-26T19:00:00-07:00',
        'isDaytime': false,
        'temperature': 83,
        'temperatureUnit': 'F',
        'temperatureTrend': null,
        'windSpeed': '13 mph',
        'windDirection': 'NW',
        'icon': 'https://api.weather.gov/icons/land/night/skc?size=small',
        'shortForecast': 'Clear',
        'detailedForecast': ''
      },
      {
        'number': 81,
        'name': '',
        'startTime': '2020-09-26T19:00:00-07:00',
        'endTime': '2020-09-26T20:00:00-07:00',
        'isDaytime': false,
        'temperature': 77,
        'temperatureUnit': 'F',
        'temperatureTrend': null,
        'windSpeed': '13 mph',
        'windDirection': 'NW',
        'icon': 'https://api.weather.gov/icons/land/night/skc?size=small',
        'shortForecast': 'Clear',
        'detailedForecast': ''
      },
      {
        'number': 82,
        'name': '',
        'startTime': '2020-09-26T20:00:00-07:00',
        'endTime': '2020-09-26T21:00:00-07:00',
        'isDaytime': false,
        'temperature': 72,
        'temperatureUnit': 'F',
        'temperatureTrend': null,
        'windSpeed': '8 mph',
        'windDirection': 'WNW',
        'icon': 'https://api.weather.gov/icons/land/night/skc?size=small',
        'shortForecast': 'Clear',
        'detailedForecast': ''
      },
      {
        'number': 83,
        'name': '',
        'startTime': '2020-09-26T21:00:00-07:00',
        'endTime': '2020-09-26T22:00:00-07:00',
        'isDaytime': false,
        'temperature': 69,
        'temperatureUnit': 'F',
        'temperatureTrend': null,
        'windSpeed': '8 mph',
        'windDirection': 'WNW',
        'icon': 'https://api.weather.gov/icons/land/night/skc?size=small',
        'shortForecast': 'Clear',
        'detailedForecast': ''
      },
      {
        'number': 84,
        'name': '',
        'startTime': '2020-09-26T22:00:00-07:00',
        'endTime': '2020-09-26T23:00:00-07:00',
        'isDaytime': false,
        'temperature': 68,
        'temperatureUnit': 'F',
        'temperatureTrend': null,
        'windSpeed': '8 mph',
        'windDirection': 'WNW',
        'icon': 'https://api.weather.gov/icons/land/night/skc?size=small',
        'shortForecast': 'Clear',
        'detailedForecast': ''
      },
      {
        'number': 85,
        'name': '',
        'startTime': '2020-09-26T23:00:00-07:00',
        'endTime': '2020-09-27T00:00:00-07:00',
        'isDaytime': false,
        'temperature': 67,
        'temperatureUnit': 'F',
        'temperatureTrend': null,
        'windSpeed': '5 mph',
        'windDirection': 'W',
        'icon': 'https://api.weather.gov/icons/land/night/skc?size=small',
        'shortForecast': 'Clear',
        'detailedForecast': ''
      },
      {
        'number': 86,
        'name': '',
        'startTime': '2020-09-27T00:00:00-07:00',
        'endTime': '2020-09-27T01:00:00-07:00',
        'isDaytime': false,
        'temperature': 66,
        'temperatureUnit': 'F',
        'temperatureTrend': null,
        'windSpeed': '5 mph',
        'windDirection': 'W',
        'icon': 'https://api.weather.gov/icons/land/night/skc?size=small',
        'shortForecast': 'Clear',
        'detailedForecast': ''
      },
      {
        'number': 87,
        'name': '',
        'startTime': '2020-09-27T01:00:00-07:00',
        'endTime': '2020-09-27T02:00:00-07:00',
        'isDaytime': false,
        'temperature': 66,
        'temperatureUnit': 'F',
        'temperatureTrend': null,
        'windSpeed': '5 mph',
        'windDirection': 'W',
        'icon': 'https://api.weather.gov/icons/land/night/skc?size=small',
        'shortForecast': 'Clear',
        'detailedForecast': ''
      },
      {
        'number': 88,
        'name': '',
        'startTime': '2020-09-27T02:00:00-07:00',
        'endTime': '2020-09-27T03:00:00-07:00',
        'isDaytime': false,
        'temperature': 65,
        'temperatureUnit': 'F',
        'temperatureTrend': null,
        'windSpeed': '5 mph',
        'windDirection': 'WNW',
        'icon': 'https://api.weather.gov/icons/land/night/skc?size=small',
        'shortForecast': 'Clear',
        'detailedForecast': ''
      },
      {
        'number': 89,
        'name': '',
        'startTime': '2020-09-27T03:00:00-07:00',
        'endTime': '2020-09-27T04:00:00-07:00',
        'isDaytime': false,
        'temperature': 64,
        'temperatureUnit': 'F',
        'temperatureTrend': null,
        'windSpeed': '5 mph',
        'windDirection': 'WNW',
        'icon': 'https://api.weather.gov/icons/land/night/skc?size=small',
        'shortForecast': 'Clear',
        'detailedForecast': ''
      },
      {
        'number': 90,
        'name': '',
        'startTime': '2020-09-27T04:00:00-07:00',
        'endTime': '2020-09-27T05:00:00-07:00',
        'isDaytime': false,
        'temperature': 64,
        'temperatureUnit': 'F',
        'temperatureTrend': null,
        'windSpeed': '5 mph',
        'windDirection': 'WNW',
        'icon': 'https://api.weather.gov/icons/land/night/skc?size=small',
        'shortForecast': 'Clear',
        'detailedForecast': ''
      },
      {
        'number': 91,
        'name': '',
        'startTime': '2020-09-27T05:00:00-07:00',
        'endTime': '2020-09-27T06:00:00-07:00',
        'isDaytime': false,
        'temperature': 64,
        'temperatureUnit': 'F',
        'temperatureTrend': null,
        'windSpeed': '5 mph',
        'windDirection': 'NNE',
        'icon': 'https://api.weather.gov/icons/land/night/skc?size=small',
        'shortForecast': 'Clear',
        'detailedForecast': ''
      },
      {
        'number': 92,
        'name': '',
        'startTime': '2020-09-27T06:00:00-07:00',
        'endTime': '2020-09-27T07:00:00-07:00',
        'isDaytime': true,
        'temperature': 63,
        'temperatureUnit': 'F',
        'temperatureTrend': null,
        'windSpeed': '5 mph',
        'windDirection': 'NNE',
        'icon': 'https://api.weather.gov/icons/land/day/skc?size=small',
        'shortForecast': 'Sunny',
        'detailedForecast': ''
      },
      {
        'number': 93,
        'name': '',
        'startTime': '2020-09-27T07:00:00-07:00',
        'endTime': '2020-09-27T08:00:00-07:00',
        'isDaytime': true,
        'temperature': 64,
        'temperatureUnit': 'F',
        'temperatureTrend': null,
        'windSpeed': '5 mph',
        'windDirection': 'NNE',
        'icon': 'https://api.weather.gov/icons/land/day/skc?size=small',
        'shortForecast': 'Sunny',
        'detailedForecast': ''
      },
      {
        'number': 94,
        'name': '',
        'startTime': '2020-09-27T08:00:00-07:00',
        'endTime': '2020-09-27T09:00:00-07:00',
        'isDaytime': true,
        'temperature': 65,
        'temperatureUnit': 'F',
        'temperatureTrend': null,
        'windSpeed': '5 mph',
        'windDirection': 'NE',
        'icon': 'https://api.weather.gov/icons/land/day/skc?size=small',
        'shortForecast': 'Sunny',
        'detailedForecast': ''
      },
      {
        'number': 95,
        'name': '',
        'startTime': '2020-09-27T09:00:00-07:00',
        'endTime': '2020-09-27T10:00:00-07:00',
        'isDaytime': true,
        'temperature': 69,
        'temperatureUnit': 'F',
        'temperatureTrend': null,
        'windSpeed': '5 mph',
        'windDirection': 'NE',
        'icon': 'https://api.weather.gov/icons/land/day/skc?size=small',
        'shortForecast': 'Sunny',
        'detailedForecast': ''
      },
      {
        'number': 96,
        'name': '',
        'startTime': '2020-09-27T10:00:00-07:00',
        'endTime': '2020-09-27T11:00:00-07:00',
        'isDaytime': true,
        'temperature': 74,
        'temperatureUnit': 'F',
        'temperatureTrend': null,
        'windSpeed': '5 mph',
        'windDirection': 'NE',
        'icon': 'https://api.weather.gov/icons/land/day/skc?size=small',
        'shortForecast': 'Sunny',
        'detailedForecast': ''
      },
      {
        'number': 97,
        'name': '',
        'startTime': '2020-09-27T11:00:00-07:00',
        'endTime': '2020-09-27T12:00:00-07:00',
        'isDaytime': true,
        'temperature': 78,
        'temperatureUnit': 'F',
        'temperatureTrend': null,
        'windSpeed': '7 mph',
        'windDirection': 'N',
        'icon': 'https://api.weather.gov/icons/land/day/skc?size=small',
        'shortForecast': 'Sunny',
        'detailedForecast': ''
      },
      {
        'number': 98,
        'name': '',
        'startTime': '2020-09-27T12:00:00-07:00',
        'endTime': '2020-09-27T13:00:00-07:00',
        'isDaytime': true,
        'temperature': 83,
        'temperatureUnit': 'F',
        'temperatureTrend': null,
        'windSpeed': '7 mph',
        'windDirection': 'N',
        'icon': 'https://api.weather.gov/icons/land/day/skc?size=small',
        'shortForecast': 'Sunny',
        'detailedForecast': ''
      },
      {
        'number': 99,
        'name': '',
        'startTime': '2020-09-27T13:00:00-07:00',
        'endTime': '2020-09-27T14:00:00-07:00',
        'isDaytime': true,
        'temperature': 86,
        'temperatureUnit': 'F',
        'temperatureTrend': null,
        'windSpeed': '7 mph',
        'windDirection': 'N',
        'icon': 'https://api.weather.gov/icons/land/day/skc?size=small',
        'shortForecast': 'Sunny',
        'detailedForecast': ''
      },
      {
        'number': 100,
        'name': '',
        'startTime': '2020-09-27T14:00:00-07:00',
        'endTime': '2020-09-27T15:00:00-07:00',
        'isDaytime': true,
        'temperature': 89,
        'temperatureUnit': 'F',
        'temperatureTrend': null,
        'windSpeed': '9 mph',
        'windDirection': 'NNW',
        'icon': 'https://api.weather.gov/icons/land/day/skc?size=small',
        'shortForecast': 'Sunny',
        'detailedForecast': ''
      },
      {
        'number': 101,
        'name': '',
        'startTime': '2020-09-27T15:00:00-07:00',
        'endTime': '2020-09-27T16:00:00-07:00',
        'isDaytime': true,
        'temperature': 91,
        'temperatureUnit': 'F',
        'temperatureTrend': null,
        'windSpeed': '9 mph',
        'windDirection': 'NNW',
        'icon': 'https://api.weather.gov/icons/land/day/skc?size=small',
        'shortForecast': 'Sunny',
        'detailedForecast': ''
      },
      {
        'number': 102,
        'name': '',
        'startTime': '2020-09-27T16:00:00-07:00',
        'endTime': '2020-09-27T17:00:00-07:00',
        'isDaytime': true,
        'temperature': 91,
        'temperatureUnit': 'F',
        'temperatureTrend': null,
        'windSpeed': '9 mph',
        'windDirection': 'NNW',
        'icon': 'https://api.weather.gov/icons/land/day/skc?size=small',
        'shortForecast': 'Sunny',
        'detailedForecast': ''
      },
      {
        'number': 103,
        'name': '',
        'startTime': '2020-09-27T17:00:00-07:00',
        'endTime': '2020-09-27T18:00:00-07:00',
        'isDaytime': true,
        'temperature': 90,
        'temperatureUnit': 'F',
        'temperatureTrend': null,
        'windSpeed': '12 mph',
        'windDirection': 'NW',
        'icon': 'https://api.weather.gov/icons/land/day/skc?size=small',
        'shortForecast': 'Sunny',
        'detailedForecast': ''
      },
      {
        'number': 104,
        'name': '',
        'startTime': '2020-09-27T18:00:00-07:00',
        'endTime': '2020-09-27T19:00:00-07:00',
        'isDaytime': false,
        'temperature': 86,
        'temperatureUnit': 'F',
        'temperatureTrend': null,
        'windSpeed': '12 mph',
        'windDirection': 'NW',
        'icon': 'https://api.weather.gov/icons/land/night/skc?size=small',
        'shortForecast': 'Clear',
        'detailedForecast': ''
      },
      {
        'number': 105,
        'name': '',
        'startTime': '2020-09-27T19:00:00-07:00',
        'endTime': '2020-09-27T20:00:00-07:00',
        'isDaytime': false,
        'temperature': 81,
        'temperatureUnit': 'F',
        'temperatureTrend': null,
        'windSpeed': '12 mph',
        'windDirection': 'NW',
        'icon': 'https://api.weather.gov/icons/land/night/skc?size=small',
        'shortForecast': 'Clear',
        'detailedForecast': ''
      },
      {
        'number': 106,
        'name': '',
        'startTime': '2020-09-27T20:00:00-07:00',
        'endTime': '2020-09-27T21:00:00-07:00',
        'isDaytime': false,
        'temperature': 76,
        'temperatureUnit': 'F',
        'temperatureTrend': null,
        'windSpeed': '7 mph',
        'windDirection': 'NW',
        'icon': 'https://api.weather.gov/icons/land/night/skc?size=small',
        'shortForecast': 'Clear',
        'detailedForecast': ''
      },
      {
        'number': 107,
        'name': '',
        'startTime': '2020-09-27T21:00:00-07:00',
        'endTime': '2020-09-27T22:00:00-07:00',
        'isDaytime': false,
        'temperature': 74,
        'temperatureUnit': 'F',
        'temperatureTrend': null,
        'windSpeed': '7 mph',
        'windDirection': 'NW',
        'icon': 'https://api.weather.gov/icons/land/night/skc?size=small',
        'shortForecast': 'Clear',
        'detailedForecast': ''
      },
      {
        'number': 108,
        'name': '',
        'startTime': '2020-09-27T22:00:00-07:00',
        'endTime': '2020-09-27T23:00:00-07:00',
        'isDaytime': false,
        'temperature': 72,
        'temperatureUnit': 'F',
        'temperatureTrend': null,
        'windSpeed': '7 mph',
        'windDirection': 'NW',
        'icon': 'https://api.weather.gov/icons/land/night/skc?size=small',
        'shortForecast': 'Clear',
        'detailedForecast': ''
      },
      {
        'number': 109,
        'name': '',
        'startTime': '2020-09-27T23:00:00-07:00',
        'endTime': '2020-09-28T00:00:00-07:00',
        'isDaytime': false,
        'temperature': 70,
        'temperatureUnit': 'F',
        'temperatureTrend': null,
        'windSpeed': '5 mph',
        'windDirection': 'W',
        'icon': 'https://api.weather.gov/icons/land/night/skc?size=small',
        'shortForecast': 'Clear',
        'detailedForecast': ''
      },
      {
        'number': 110,
        'name': '',
        'startTime': '2020-09-28T00:00:00-07:00',
        'endTime': '2020-09-28T01:00:00-07:00',
        'isDaytime': false,
        'temperature': 69,
        'temperatureUnit': 'F',
        'temperatureTrend': null,
        'windSpeed': '5 mph',
        'windDirection': 'W',
        'icon': 'https://api.weather.gov/icons/land/night/skc?size=small',
        'shortForecast': 'Clear',
        'detailedForecast': ''
      },
      {
        'number': 111,
        'name': '',
        'startTime': '2020-09-28T01:00:00-07:00',
        'endTime': '2020-09-28T02:00:00-07:00',
        'isDaytime': false,
        'temperature': 68,
        'temperatureUnit': 'F',
        'temperatureTrend': null,
        'windSpeed': '5 mph',
        'windDirection': 'W',
        'icon': 'https://api.weather.gov/icons/land/night/skc?size=small',
        'shortForecast': 'Clear',
        'detailedForecast': ''
      },
      {
        'number': 112,
        'name': '',
        'startTime': '2020-09-28T02:00:00-07:00',
        'endTime': '2020-09-28T03:00:00-07:00',
        'isDaytime': false,
        'temperature': 68,
        'temperatureUnit': 'F',
        'temperatureTrend': null,
        'windSpeed': '5 mph',
        'windDirection': 'SSE',
        'icon': 'https://api.weather.gov/icons/land/night/skc?size=small',
        'shortForecast': 'Clear',
        'detailedForecast': ''
      },
      {
        'number': 113,
        'name': '',
        'startTime': '2020-09-28T03:00:00-07:00',
        'endTime': '2020-09-28T04:00:00-07:00',
        'isDaytime': false,
        'temperature': 67,
        'temperatureUnit': 'F',
        'temperatureTrend': null,
        'windSpeed': '5 mph',
        'windDirection': 'SSE',
        'icon': 'https://api.weather.gov/icons/land/night/skc?size=small',
        'shortForecast': 'Clear',
        'detailedForecast': ''
      },
      {
        'number': 114,
        'name': '',
        'startTime': '2020-09-28T04:00:00-07:00',
        'endTime': '2020-09-28T05:00:00-07:00',
        'isDaytime': false,
        'temperature': 67,
        'temperatureUnit': 'F',
        'temperatureTrend': null,
        'windSpeed': '5 mph',
        'windDirection': 'SSE',
        'icon': 'https://api.weather.gov/icons/land/night/skc?size=small',
        'shortForecast': 'Clear',
        'detailedForecast': ''
      },
      {
        'number': 115,
        'name': '',
        'startTime': '2020-09-28T05:00:00-07:00',
        'endTime': '2020-09-28T06:00:00-07:00',
        'isDaytime': false,
        'temperature': 66,
        'temperatureUnit': 'F',
        'temperatureTrend': null,
        'windSpeed': '5 mph',
        'windDirection': 'NE',
        'icon': 'https://api.weather.gov/icons/land/night/skc?size=small',
        'shortForecast': 'Clear',
        'detailedForecast': ''
      },
      {
        'number': 116,
        'name': '',
        'startTime': '2020-09-28T06:00:00-07:00',
        'endTime': '2020-09-28T07:00:00-07:00',
        'isDaytime': true,
        'temperature': 66,
        'temperatureUnit': 'F',
        'temperatureTrend': null,
        'windSpeed': '5 mph',
        'windDirection': 'NE',
        'icon': 'https://api.weather.gov/icons/land/day/skc?size=small',
        'shortForecast': 'Sunny',
        'detailedForecast': ''
      },
      {
        'number': 117,
        'name': '',
        'startTime': '2020-09-28T07:00:00-07:00',
        'endTime': '2020-09-28T08:00:00-07:00',
        'isDaytime': true,
        'temperature': 66,
        'temperatureUnit': 'F',
        'temperatureTrend': null,
        'windSpeed': '5 mph',
        'windDirection': 'NE',
        'icon': 'https://api.weather.gov/icons/land/day/skc?size=small',
        'shortForecast': 'Sunny',
        'detailedForecast': ''
      },
      {
        'number': 118,
        'name': '',
        'startTime': '2020-09-28T08:00:00-07:00',
        'endTime': '2020-09-28T09:00:00-07:00',
        'isDaytime': true,
        'temperature': 67,
        'temperatureUnit': 'F',
        'temperatureTrend': null,
        'windSpeed': '5 mph',
        'windDirection': 'NE',
        'icon': 'https://api.weather.gov/icons/land/day/few?size=small',
        'shortForecast': 'Sunny',
        'detailedForecast': ''
      },
      {
        'number': 119,
        'name': '',
        'startTime': '2020-09-28T09:00:00-07:00',
        'endTime': '2020-09-28T10:00:00-07:00',
        'isDaytime': true,
        'temperature': 70,
        'temperatureUnit': 'F',
        'temperatureTrend': null,
        'windSpeed': '5 mph',
        'windDirection': 'NE',
        'icon': 'https://api.weather.gov/icons/land/day/few?size=small',
        'shortForecast': 'Sunny',
        'detailedForecast': ''
      },
      {
        'number': 120,
        'name': '',
        'startTime': '2020-09-28T10:00:00-07:00',
        'endTime': '2020-09-28T11:00:00-07:00',
        'isDaytime': true,
        'temperature': 74,
        'temperatureUnit': 'F',
        'temperatureTrend': null,
        'windSpeed': '5 mph',
        'windDirection': 'NE',
        'icon': 'https://api.weather.gov/icons/land/day/few?size=small',
        'shortForecast': 'Sunny',
        'detailedForecast': ''
      },
      {
        'number': 121,
        'name': '',
        'startTime': '2020-09-28T11:00:00-07:00',
        'endTime': '2020-09-28T12:00:00-07:00',
        'isDaytime': true,
        'temperature': 78,
        'temperatureUnit': 'F',
        'temperatureTrend': null,
        'windSpeed': '5 mph',
        'windDirection': 'NNE',
        'icon': 'https://api.weather.gov/icons/land/day/skc?size=small',
        'shortForecast': 'Sunny',
        'detailedForecast': ''
      },
      {
        'number': 122,
        'name': '',
        'startTime': '2020-09-28T12:00:00-07:00',
        'endTime': '2020-09-28T13:00:00-07:00',
        'isDaytime': true,
        'temperature': 81,
        'temperatureUnit': 'F',
        'temperatureTrend': null,
        'windSpeed': '5 mph',
        'windDirection': 'NNE',
        'icon': 'https://api.weather.gov/icons/land/day/skc?size=small',
        'shortForecast': 'Sunny',
        'detailedForecast': ''
      },
      {
        'number': 123,
        'name': '',
        'startTime': '2020-09-28T13:00:00-07:00',
        'endTime': '2020-09-28T14:00:00-07:00',
        'isDaytime': true,
        'temperature': 84,
        'temperatureUnit': 'F',
        'temperatureTrend': null,
        'windSpeed': '5 mph',
        'windDirection': 'NNE',
        'icon': 'https://api.weather.gov/icons/land/day/skc?size=small',
        'shortForecast': 'Sunny',
        'detailedForecast': ''
      },
      {
        'number': 124,
        'name': '',
        'startTime': '2020-09-28T14:00:00-07:00',
        'endTime': '2020-09-28T15:00:00-07:00',
        'isDaytime': true,
        'temperature': 87,
        'temperatureUnit': 'F',
        'temperatureTrend': null,
        'windSpeed': '9 mph',
        'windDirection': 'NW',
        'icon': 'https://api.weather.gov/icons/land/day/skc?size=small',
        'shortForecast': 'Sunny',
        'detailedForecast': ''
      },
      {
        'number': 125,
        'name': '',
        'startTime': '2020-09-28T15:00:00-07:00',
        'endTime': '2020-09-28T16:00:00-07:00',
        'isDaytime': true,
        'temperature': 88,
        'temperatureUnit': 'F',
        'temperatureTrend': null,
        'windSpeed': '9 mph',
        'windDirection': 'NW',
        'icon': 'https://api.weather.gov/icons/land/day/skc?size=small',
        'shortForecast': 'Sunny',
        'detailedForecast': ''
      },
      {
        'number': 126,
        'name': '',
        'startTime': '2020-09-28T16:00:00-07:00',
        'endTime': '2020-09-28T17:00:00-07:00',
        'isDaytime': true,
        'temperature': 89,
        'temperatureUnit': 'F',
        'temperatureTrend': null,
        'windSpeed': '9 mph',
        'windDirection': 'NW',
        'icon': 'https://api.weather.gov/icons/land/day/skc?size=small',
        'shortForecast': 'Sunny',
        'detailedForecast': ''
      },
      {
        'number': 127,
        'name': '',
        'startTime': '2020-09-28T17:00:00-07:00',
        'endTime': '2020-09-28T18:00:00-07:00',
        'isDaytime': true,
        'temperature': 87,
        'temperatureUnit': 'F',
        'temperatureTrend': null,
        'windSpeed': '8 mph',
        'windDirection': 'WNW',
        'icon': 'https://api.weather.gov/icons/land/day/skc?size=small',
        'shortForecast': 'Sunny',
        'detailedForecast': ''
      },
      {
        'number': 128,
        'name': '',
        'startTime': '2020-09-28T18:00:00-07:00',
        'endTime': '2020-09-28T19:00:00-07:00',
        'isDaytime': false,
        'temperature': 84,
        'temperatureUnit': 'F',
        'temperatureTrend': null,
        'windSpeed': '8 mph',
        'windDirection': 'WNW',
        'icon': 'https://api.weather.gov/icons/land/night/skc?size=small',
        'shortForecast': 'Clear',
        'detailedForecast': ''
      },
      {
        'number': 129,
        'name': '',
        'startTime': '2020-09-28T19:00:00-07:00',
        'endTime': '2020-09-28T20:00:00-07:00',
        'isDaytime': false,
        'temperature': 80,
        'temperatureUnit': 'F',
        'temperatureTrend': null,
        'windSpeed': '8 mph',
        'windDirection': 'WNW',
        'icon': 'https://api.weather.gov/icons/land/night/skc?size=small',
        'shortForecast': 'Clear',
        'detailedForecast': ''
      },
      {
        'number': 130,
        'name': '',
        'startTime': '2020-09-28T20:00:00-07:00',
        'endTime': '2020-09-28T21:00:00-07:00',
        'isDaytime': false,
        'temperature': 76,
        'temperatureUnit': 'F',
        'temperatureTrend': null,
        'windSpeed': '6 mph',
        'windDirection': 'WNW',
        'icon': 'https://api.weather.gov/icons/land/night/skc?size=small',
        'shortForecast': 'Clear',
        'detailedForecast': ''
      },
      {
        'number': 131,
        'name': '',
        'startTime': '2020-09-28T21:00:00-07:00',
        'endTime': '2020-09-28T22:00:00-07:00',
        'isDaytime': false,
        'temperature': 73,
        'temperatureUnit': 'F',
        'temperatureTrend': null,
        'windSpeed': '6 mph',
        'windDirection': 'WNW',
        'icon': 'https://api.weather.gov/icons/land/night/skc?size=small',
        'shortForecast': 'Clear',
        'detailedForecast': ''
      },
      {
        'number': 132,
        'name': '',
        'startTime': '2020-09-28T22:00:00-07:00',
        'endTime': '2020-09-28T23:00:00-07:00',
        'isDaytime': false,
        'temperature': 72,
        'temperatureUnit': 'F',
        'temperatureTrend': null,
        'windSpeed': '6 mph',
        'windDirection': 'WNW',
        'icon': 'https://api.weather.gov/icons/land/night/skc?size=small',
        'shortForecast': 'Clear',
        'detailedForecast': ''
      },
      {
        'number': 133,
        'name': '',
        'startTime': '2020-09-28T23:00:00-07:00',
        'endTime': '2020-09-29T00:00:00-07:00',
        'isDaytime': false,
        'temperature': 70,
        'temperatureUnit': 'F',
        'temperatureTrend': null,
        'windSpeed': '2 mph',
        'windDirection': 'W',
        'icon': 'https://api.weather.gov/icons/land/night/skc?size=small',
        'shortForecast': 'Clear',
        'detailedForecast': ''
      },
      {
        'number': 134,
        'name': '',
        'startTime': '2020-09-29T00:00:00-07:00',
        'endTime': '2020-09-29T01:00:00-07:00',
        'isDaytime': false,
        'temperature': 70,
        'temperatureUnit': 'F',
        'temperatureTrend': null,
        'windSpeed': '2 mph',
        'windDirection': 'W',
        'icon': 'https://api.weather.gov/icons/land/night/skc?size=small',
        'shortForecast': 'Clear',
        'detailedForecast': ''
      },
      {
        'number': 135,
        'name': '',
        'startTime': '2020-09-29T01:00:00-07:00',
        'endTime': '2020-09-29T02:00:00-07:00',
        'isDaytime': false,
        'temperature': 69,
        'temperatureUnit': 'F',
        'temperatureTrend': null,
        'windSpeed': '2 mph',
        'windDirection': 'W',
        'icon': 'https://api.weather.gov/icons/land/night/skc?size=small',
        'shortForecast': 'Clear',
        'detailedForecast': ''
      },
      {
        'number': 136,
        'name': '',
        'startTime': '2020-09-29T02:00:00-07:00',
        'endTime': '2020-09-29T03:00:00-07:00',
        'isDaytime': false,
        'temperature': 68,
        'temperatureUnit': 'F',
        'temperatureTrend': null,
        'windSpeed': '2 mph',
        'windDirection': 'WSW',
        'icon': 'https://api.weather.gov/icons/land/night/skc?size=small',
        'shortForecast': 'Clear',
        'detailedForecast': ''
      },
      {
        'number': 137,
        'name': '',
        'startTime': '2020-09-29T03:00:00-07:00',
        'endTime': '2020-09-29T04:00:00-07:00',
        'isDaytime': false,
        'temperature': 67,
        'temperatureUnit': 'F',
        'temperatureTrend': null,
        'windSpeed': '2 mph',
        'windDirection': 'WSW',
        'icon': 'https://api.weather.gov/icons/land/night/skc?size=small',
        'shortForecast': 'Clear',
        'detailedForecast': ''
      },
      {
        'number': 138,
        'name': '',
        'startTime': '2020-09-29T04:00:00-07:00',
        'endTime': '2020-09-29T05:00:00-07:00',
        'isDaytime': false,
        'temperature': 67,
        'temperatureUnit': 'F',
        'temperatureTrend': null,
        'windSpeed': '2 mph',
        'windDirection': 'WSW',
        'icon': 'https://api.weather.gov/icons/land/night/skc?size=small',
        'shortForecast': 'Clear',
        'detailedForecast': ''
      },
      {
        'number': 139,
        'name': '',
        'startTime': '2020-09-29T05:00:00-07:00',
        'endTime': '2020-09-29T06:00:00-07:00',
        'isDaytime': false,
        'temperature': 66,
        'temperatureUnit': 'F',
        'temperatureTrend': null,
        'windSpeed': '2 mph',
        'windDirection': 'W',
        'icon': 'https://api.weather.gov/icons/land/night/skc?size=small',
        'shortForecast': 'Clear',
        'detailedForecast': ''
      },
      {
        'number': 140,
        'name': '',
        'startTime': '2020-09-29T06:00:00-07:00',
        'endTime': '2020-09-29T07:00:00-07:00',
        'isDaytime': true,
        'temperature': 66,
        'temperatureUnit': 'F',
        'temperatureTrend': null,
        'windSpeed': '2 mph',
        'windDirection': 'W',
        'icon': 'https://api.weather.gov/icons/land/day/skc?size=small',
        'shortForecast': 'Sunny',
        'detailedForecast': ''
      },
      {
        'number': 141,
        'name': '',
        'startTime': '2020-09-29T07:00:00-07:00',
        'endTime': '2020-09-29T08:00:00-07:00',
        'isDaytime': true,
        'temperature': 66,
        'temperatureUnit': 'F',
        'temperatureTrend': null,
        'windSpeed': '2 mph',
        'windDirection': 'W',
        'icon': 'https://api.weather.gov/icons/land/day/skc?size=small',
        'shortForecast': 'Sunny',
        'detailedForecast': ''
      },
      {
        'number': 142,
        'name': '',
        'startTime': '2020-09-29T08:00:00-07:00',
        'endTime': '2020-09-29T09:00:00-07:00',
        'isDaytime': true,
        'temperature': 67,
        'temperatureUnit': 'F',
        'temperatureTrend': null,
        'windSpeed': '2 mph',
        'windDirection': 'NNW',
        'icon': 'https://api.weather.gov/icons/land/day/few?size=small',
        'shortForecast': 'Sunny',
        'detailedForecast': ''
      },
      {
        'number': 143,
        'name': '',
        'startTime': '2020-09-29T09:00:00-07:00',
        'endTime': '2020-09-29T10:00:00-07:00',
        'isDaytime': true,
        'temperature': 70,
        'temperatureUnit': 'F',
        'temperatureTrend': null,
        'windSpeed': '2 mph',
        'windDirection': 'NNW',
        'icon': 'https://api.weather.gov/icons/land/day/few?size=small',
        'shortForecast': 'Sunny',
        'detailedForecast': ''
      },
      {
        'number': 144,
        'name': '',
        'startTime': '2020-09-29T10:00:00-07:00',
        'endTime': '2020-09-29T11:00:00-07:00',
        'isDaytime': true,
        'temperature': 74,
        'temperatureUnit': 'F',
        'temperatureTrend': null,
        'windSpeed': '2 mph',
        'windDirection': 'NNW',
        'icon': 'https://api.weather.gov/icons/land/day/few?size=small',
        'shortForecast': 'Sunny',
        'detailedForecast': ''
      },
      {
        'number': 145,
        'name': '',
        'startTime': '2020-09-29T11:00:00-07:00',
        'endTime': '2020-09-29T12:00:00-07:00',
        'isDaytime': true,
        'temperature': 78,
        'temperatureUnit': 'F',
        'temperatureTrend': null,
        'windSpeed': '2 mph',
        'windDirection': 'NNW',
        'icon': 'https://api.weather.gov/icons/land/day/skc?size=small',
        'shortForecast': 'Sunny',
        'detailedForecast': ''
      },
      {
        'number': 146,
        'name': '',
        'startTime': '2020-09-29T12:00:00-07:00',
        'endTime': '2020-09-29T13:00:00-07:00',
        'isDaytime': true,
        'temperature': 82,
        'temperatureUnit': 'F',
        'temperatureTrend': null,
        'windSpeed': '2 mph',
        'windDirection': 'NNW',
        'icon': 'https://api.weather.gov/icons/land/day/skc?size=small',
        'shortForecast': 'Sunny',
        'detailedForecast': ''
      },
      {
        'number': 147,
        'name': '',
        'startTime': '2020-09-29T13:00:00-07:00',
        'endTime': '2020-09-29T14:00:00-07:00',
        'isDaytime': true,
        'temperature': 85,
        'temperatureUnit': 'F',
        'temperatureTrend': null,
        'windSpeed': '2 mph',
        'windDirection': 'NNW',
        'icon': 'https://api.weather.gov/icons/land/day/skc?size=small',
        'shortForecast': 'Sunny',
        'detailedForecast': ''
      },
      {
        'number': 148,
        'name': '',
        'startTime': '2020-09-29T14:00:00-07:00',
        'endTime': '2020-09-29T15:00:00-07:00',
        'isDaytime': true,
        'temperature': 87,
        'temperatureUnit': 'F',
        'temperatureTrend': null,
        'windSpeed': '7 mph',
        'windDirection': 'NW',
        'icon': 'https://api.weather.gov/icons/land/day/skc?size=small',
        'shortForecast': 'Sunny',
        'detailedForecast': ''
      },
      {
        'number': 149,
        'name': '',
        'startTime': '2020-09-29T15:00:00-07:00',
        'endTime': '2020-09-29T16:00:00-07:00',
        'isDaytime': true,
        'temperature': 89,
        'temperatureUnit': 'F',
        'temperatureTrend': null,
        'windSpeed': '7 mph',
        'windDirection': 'NW',
        'icon': 'https://api.weather.gov/icons/land/day/skc?size=small',
        'shortForecast': 'Sunny',
        'detailedForecast': ''
      },
      {
        'number': 150,
        'name': '',
        'startTime': '2020-09-29T16:00:00-07:00',
        'endTime': '2020-09-29T17:00:00-07:00',
        'isDaytime': true,
        'temperature': 89,
        'temperatureUnit': 'F',
        'temperatureTrend': null,
        'windSpeed': '7 mph',
        'windDirection': 'NW',
        'icon': 'https://api.weather.gov/icons/land/day/skc?size=small',
        'shortForecast': 'Sunny',
        'detailedForecast': ''
      },
      {
        'number': 151,
        'name': '',
        'startTime': '2020-09-29T17:00:00-07:00',
        'endTime': '2020-09-29T18:00:00-07:00',
        'isDaytime': true,
        'temperature': 88,
        'temperatureUnit': 'F',
        'temperatureTrend': null,
        'windSpeed': '9 mph',
        'windDirection': 'WNW',
        'icon': 'https://api.weather.gov/icons/land/day/skc?size=small',
        'shortForecast': 'Sunny',
        'detailedForecast': ''
      },
      {
        'number': 152,
        'name': '',
        'startTime': '2020-09-29T18:00:00-07:00',
        'endTime': '2020-09-29T19:00:00-07:00',
        'isDaytime': false,
        'temperature': 84,
        'temperatureUnit': 'F',
        'temperatureTrend': null,
        'windSpeed': '9 mph',
        'windDirection': 'WNW',
        'icon': 'https://api.weather.gov/icons/land/night/skc?size=small',
        'shortForecast': 'Clear',
        'detailedForecast': ''
      },
      {
        'number': 153,
        'name': '',
        'startTime': '2020-09-29T19:00:00-07:00',
        'endTime': '2020-09-29T20:00:00-07:00',
        'isDaytime': false,
        'temperature': 79,
        'temperatureUnit': 'F',
        'temperatureTrend': null,
        'windSpeed': '9 mph',
        'windDirection': 'WNW',
        'icon': 'https://api.weather.gov/icons/land/night/skc?size=small',
        'shortForecast': 'Clear',
        'detailedForecast': ''
      },
      {
        'number': 154,
        'name': '',
        'startTime': '2020-09-29T20:00:00-07:00',
        'endTime': '2020-09-29T21:00:00-07:00',
        'isDaytime': false,
        'temperature': 75,
        'temperatureUnit': 'F',
        'temperatureTrend': null,
        'windSpeed': '6 mph',
        'windDirection': 'WNW',
        'icon': 'https://api.weather.gov/icons/land/night/few?size=small',
        'shortForecast': 'Mostly Clear',
        'detailedForecast': ''
      },
      {
        'number': 155,
        'name': '',
        'startTime': '2020-09-29T21:00:00-07:00',
        'endTime': '2020-09-29T22:00:00-07:00',
        'isDaytime': false,
        'temperature': 72,
        'temperatureUnit': 'F',
        'temperatureTrend': null,
        'windSpeed': '6 mph',
        'windDirection': 'WNW',
        'icon': 'https://api.weather.gov/icons/land/night/few?size=small',
        'shortForecast': 'Mostly Clear',
        'detailedForecast': ''
      },
      {
        'number': 156,
        'name': '',
        'startTime': '2020-09-29T22:00:00-07:00',
        'endTime': '2020-09-29T23:00:00-07:00',
        'isDaytime': false,
        'temperature': 70,
        'temperatureUnit': 'F',
        'temperatureTrend': null,
        'windSpeed': '6 mph',
        'windDirection': 'WNW',
        'icon': 'https://api.weather.gov/icons/land/night/few?size=small',
        'shortForecast': 'Mostly Clear',
        'detailedForecast': ''
      }
    ]
  };
}

